### ISSUE TITLE
How I should change it to paginate a search result?

### ISSUE THREAD

**Issue by satrianivzla** [BenGriffiths/pdo-mysqli-pagination#18]
Hi there 
How I should change it to paginate a search result?
I already made it able to work with pretty url but I have a doubt about how others changes I need to make to have for example the results like www.mysite.com/search/string/1, where search is the page, string is the value and of course the page number

**Comment by BenGriffiths** [comment]
When you set your options you can define the URL structure, such as:

```php
$searchVar = 'Whatever';

$options = array(  
    'url'        => 'http://www.mysite.com/search/'.$searchVar.'/*VAR*'
);
```
That's clearly over simplified, but you should be able to see how it can be set.
