### ISSUE TITLE
Make project Composer friendly

### ISSUE THREAD

**Issue by smartclash** [BenGriffiths/pdo-mysqli-pagination#23]
Hey there. Your project is awesome and I use it for my commercial web application. Many people around the globe use composer widely to reduce work burden and make the script execute faster.

You can make sure that your project is also friendly to composer by uploading this script to https://packagist.org/ and autoloading your script by either using PSR-4 standards or using PSR-0 standards. 

Doing this will make sure that your script is ready to be plugged in and played without any hassle. Let composer manage the dirty work. Cheers 🥂

**Comment by PetengDedet** [comment]
+1

**Comment by e-ht** [comment]
@smartclash @PetengDedet 

It's not a huge, ever changing repo. Per the Pagagist page you linked, you can just as easily fork and publish with Composer.

**Comment by smartclash** [comment]
Cleaning up my open issues. And, what you have said is right @e-ht. Thanks for this :)
